In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1.shape)

[1 2 3 4 5]
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)
# print(arr2)

array([[1, 2, 3, 4, 5]])

In [8]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [12]:
#slicing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)

arr[0][0]

arr[2:3]

arr[1:,2:]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


array([[ 8,  9, 10],
       [13, 14, 15]])

In [16]:
#logical operations
data=np.array([1,2,3,4,5,6,7,8,9])

data>5

data[(data>5) & (data<=8)]

array([6, 7, 8])